### ISSUE TITLE
invalid option: --with-proj-dir=/usr/local/bin for command gem install rgeo-proj4 --with-proj-dir=/usr/local/bin

### ISSUE THREAD

**Issue by ddd1600** [rgeo/rgeo-proj4#12]
Fundamentally, the issue is this error:

RGeo::Error::UnsupportedOperation: Coordinate system 'proj4' is not supported.

I've been using RGeo for years. Have never had to use the rgeo-proj4 gem, which I've replaced in my Gemfile from the previous 'rgeo' gem. I've followed all the online guides on making sure proj is already installed, making sure its located where it should be, but RGeo still can't find the Proj library.

Please help! Thanks

**Comment by keithdoggett** [comment]
I'm not sure why that build flag isn't working. I haven't been able to get it to work either, but I'd imagine you shouldn't have to specify `/usr/local/bin` since that should be in your PATH.

Is there any output when you install it?

What ruby code are you trying?

Does this work?

```rb
require 'rgeo'
require 'rgeo/proj4'

RGeo::CoordSys::Proj4.supported?
# => true
```

**Comment by armahillo** [comment]
You have to put `--` before the `--with-proj-dir` option. So your command would look like ths: 
```bash
gem install rgeo-proj4 -- --with-proj-dir=/usr/local/bin 
```

This may or may not fix your issue

**Comment by keithdoggett** [comment]
@armahillo that's correct. Thanks!
